$NetBSD$

--- ../librespot/audio/Cargo.toml.orig	2018-11-19 14:03:35.000000000 +0000
+++ ../librespot/audio/Cargo.toml
@@ -17,7 +17,8 @@ num-traits = "0.1.36"
 rust-crypto = "0.2.36"
 tempfile = "2.1"
 
-tremor = { git = "https://github.com/plietar/rust-tremor", optional = true }
+#tremor = { git = "https://github.com/plietar/rust-tremor", optional = true }
+tremor = { path = "../../rust-tremor", optional = true }
 vorbis = { version ="0.1.0", optional = true }
 
 [features]
