$NetBSD$

--- ../librespot/connect/Cargo.toml.orig	2018-11-19 14:03:35.000000000 +0000
+++ ../librespot/connect/Cargo.toml
@@ -26,7 +26,8 @@ tokio-core = "0.1.2"
 url = "1.3"
 
 dns-sd = { version = "0.1.3", optional = true }
-mdns = { git = "https://github.com/plietar/rust-mdns", optional = true }
+#mdns = { git = "https://github.com/plietar/rust-mdns", optional = true }
+mdns = { path = "../../rust-mdns", optional = true }
 
 [features]
 default = ["mdns"]
